---
scireum_volumes: &scireum_volumes
  - name: docker_socket
    path: /var/run/docker.sock
  - name: m2
    path: /root/.m2
  - name: docker_config
    path: /root/.docker

kind: pipeline
name: default

clone:
  depth: 100

steps:
  - name: publish_develop
    image: jgescireum/buildx:latest
    settings:
      registry: hub.scireum.com
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - hub.scireum.com/sellsite/test:latest
    environment:
      PLUGIN_EXPERIMENTAL: true
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    volumes: *scireum_volumes
    when:
      branch:
        - main
      event:
        - push


volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker
  - name: m2
    host:
      path: /root/.m2
