---
scireum_volumes: &scireum_volumes
  - name: docker_socket
    path: /var/run/docker.sock
  - name: m2
    path: /root/.m2


kind: pipeline
name: default

clone:
  depth: 100

steps:
  - name: publish_develop
    image: scireum/sirius-build-jdk17
    commands:
      - docker pull scireumskip/quasar:3.0.0
    volumes: *scireum_volumes
    when:
      branch:
        - main
      event:
        - push

  
volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker
  - name: m2
    host:
      path: /root/.m2
